### ISSUE TITLE
AreTomo refineFlag==1 is not accessible through WarpTools

### ISSUE THREAD

**Issue by amineuron** [warpem/warp#223]
Hi Alister,

I noticed in the AreTomo documentation that the refineFlag can also be set to 1, which indicates refining the input value and calculating the tilt axis at each tilt angle. However, in WarpWorker, it appears the assumption is that this flag can only be 0 or -1:

https://github.com/warpem/warp/blob/cd1315f22b3f67b09800cacabe241698af569c8b/WarpWorker/WarpWorker.cs#L351

It seems like this variable has been treated as a boolean by design:

https://github.com/warpem/warp/blob/cd1315f22b3f67b09800cacabe241698af569c8b/WarpTools/Commands/Tiltseries/AreTomoTiltseries.cs#L78

This refineFlag was useful for me, it could be an enhancement to allow its usage through the CLI. (or making this option accessible with setting --axis_iter -1) 

Thank you for considering this suggestion!

**Comment by alisterburt** [comment]
Hi @amineuron - thanks for the suggestion! The tilt axis angle is a fixed physical parameter which depends on magnification, it only really makes sense to fit a single parameter here... (even better to fit across a whole dataset)

Because of that I don't think we will add this, the purpose of the wrappers is to provide a simple way to run AreTomo for our users, not to stay 100% in sync with AreTomo or expose all of its functionality. You are of course welcome to run AreTomo yourself and import the results, you are not obliged to use our wrapper - please see https://warpem.com/reference/warptools/custom_tilt_series_alignments/ for details 🙂

**Comment by amineuron** [comment]
Hi Alister,

Thank you for explaining the considerations behind the current implementation. 

You're absolutely right maybe was the old tomo5 or microscope problem because the new data from the microscope, it doesn’t exhibit the varying tilt axis issue. However, I still notice some differences between Tomo5 and SerialEM, which I could benefit --initial_axis flag. I’m curious—though it might be a basic question—why do we adjust the tilt axis from -95 to -85.6 in the tutorial, despite knowing its actual value?

Thanks again for your support and guidance!

Amin

**Comment by alisterburt** [comment]
@amineuron great to hear! I think the reason for moving to -85.6 was simply seeing that -95 did not appear to fit the data and -85.6 was the value we observed fitting well
